from .methods_users import *
from .auth import *
from .domaine import *
from .categorie import *
from .parcours import *
from .attemptedquestion import *
from .choice import *
from .question import *
from .parcours import *
from .quizzprofile import *
from .tutorial import *
from .play import *
from .recommendation import *
